"""empty message

Revision ID: 365563032dc5
Revises: 
Create Date: 2021-05-23 21:09:13.325529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365563032dc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_pid_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('note_text_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_pid_linker_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=True),
    sa.Column('note_pid_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note_model.id'], ),
    sa.ForeignKeyConstraint(['note_pid_id'], ['note_pid_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_text_linker_model',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=True),
    sa.Column('note_text_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note_model.id'], ),
    sa.ForeignKeyConstraint(['note_text_id'], ['note_text_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_text_linker_model')
    op.drop_table('note_pid_linker_model')
    op.drop_table('note_text_model')
    op.drop_table('note_pid_model')
    op.drop_table('note_model')
    # ### end Alembic commands ###
